// ═══════════════════════════════════════════════
// DATA — definice levelů, farem, manažerů, upgradů
// ═══════════════════════════════════════════════

export const LEVELS = [
  // ── LEVEL 0: Farmářský magnát ──────────────────
  {
    id: 0,
    name: 'Farmářský magnát',
    emoji: '🌱',
    desc: 'Vybuduj farmářské impérium od jahodové zahrádky po chilli impérium!',
    color: '#00ffb3',
    businesses: [
      { id:0, name:'Jahodová zahrádka', emoji:'🍓', color:'#f85149', bg:'rgba(248,81,73,0.15)',
        baseCost:4, baseIncome:1.0, timer:1.5, unlockCost:0,
        milestones:[{at:10,mult:2,label:'×2'},{at:25,mult:3,label:'×3'},{at:50,mult:2,label:'×2'},{at:100,mult:5,label:'×5'},{at:200,mult:2,label:'×2'},{at:300,mult:10,label:'×10'},{at:500,mult:2,label:'×2'}]},
      { id:1, name:'Mrkvové pole', emoji:'🥕', color:'#f0883e', bg:'rgba(240,136,62,0.15)',
        baseCost:60, baseIncome:8, timer:3, unlockCost:0,
        milestones:[{at:10,mult:2,label:'×2'},{at:25,mult:2,label:'×2'},{at:50,mult:3,label:'×3'},{at:100,mult:2,label:'×2'},{at:200,mult:5,label:'×5'},{at:400,mult:2,label:'×2'}]},
      { id:2, name:'Rajčatový skleník', emoji:'🍅', color:'#f85149', bg:'rgba(220,38,38,0.12)',
        baseCost:720, baseIncome:60, timer:6, unlockCost:200,
        milestones:[{at:10,mult:2,label:'×2'},{at:25,mult:3,label:'×3'},{at:75,mult:2,label:'×2'},{at:100,mult:2,label:'×2'},{at:200,mult:5,label:'×5'},{at:300,mult:3,label:'×3'}]},
      { id:3, name:'Borůvkový háj', emoji:'🫐', color:'#a371f7', bg:'rgba(163,113,247,0.15)',
        baseCost:8640, baseIncome:500, timer:12, unlockCost:2000,
        milestones:[{at:10,mult:2,label:'×2'},{at:25,mult:2,label:'×2'},{at:50,mult:5,label:'×5'},{at:100,mult:2,label:'×2'},{at:250,mult:3,label:'×3'},{at:500,mult:10,label:'×10'}]},
      { id:4, name:'Brokolicová plantáž', emoji:'🥦', color:'#3fb950', bg:'rgba(63,185,80,0.15)',
        baseCost:103680, baseIncome:4000, timer:24, unlockCost:20000,
        milestones:[{at:10,mult:2,label:'×2'},{at:25,mult:2,label:'×2'},{at:50,mult:3,label:'×3'},{at:100,mult:5,label:'×5'},{at:200,mult:2,label:'×2'},{at:400,mult:5,label:'×5'}]},
      { id:5, name:'Vinohrad hroznů', emoji:'🍇', color:'#8957e5', bg:'rgba(137,87,229,0.15)',
        baseCost:1244160, baseIncome:30000, timer:48, unlockCost:200000,
        milestones:[{at:10,mult:2,label:'×2'},{at:25,mult:3,label:'×3'},{at:50,mult:2,label:'×2'},{at:100,mult:5,label:'×5'},{at:200,mult:3,label:'×3'},{at:300,mult:2,label:'×2'}]},
      { id:6, name:'Melounová farma', emoji:'🍉', color:'#39d353', bg:'rgba(57,211,83,0.12)',
        baseCost:14929920, baseIncome:200000, timer:96, unlockCost:2000000,
        milestones:[{at:10,mult:2,label:'×2'},{at:25,mult:2,label:'×2'},{at:50,mult:3,label:'×3'},{at:100,mult:10,label:'×10'},{at:200,mult:2,label:'×2'},{at:350,mult:5,label:'×5'}]},
      { id:7, name:'Avokádový sad', emoji:'🥑', color:'#7ee787', bg:'rgba(126,231,135,0.12)',
        baseCost:179159040, baseIncome:1500000, timer:180, unlockCost:25000000,
        milestones:[{at:10,mult:2,label:'×2'},{at:25,mult:5,label:'×5'},{at:50,mult:2,label:'×2'},{at:100,mult:3,label:'×3'},{at:200,mult:5,label:'×5'},{at:400,mult:2,label:'×2'}]},
      { id:8, name:'Ananasová plantáž', emoji:'🍍', color:'#e3b341', bg:'rgba(227,179,65,0.12)',
        baseCost:2149908480, baseIncome:12000000, timer:360, unlockCost:300000000,
        milestones:[{at:10,mult:2,label:'×2'},{at:25,mult:3,label:'×3'},{at:50,mult:5,label:'×5'},{at:100,mult:2,label:'×2'},{at:200,mult:10,label:'×10'},{at:300,mult:3,label:'×3'}]},
      { id:9, name:'Chilli impérium', emoji:'🌶️', color:'#f85149', bg:'rgba(248,81,73,0.12)',
        baseCost:25798901760, baseIncome:100000000, timer:600, unlockCost:3000000000,
        milestones:[{at:10,mult:2,label:'×2'},{at:25,mult:5,label:'×5'},{at:50,mult:3,label:'×3'},{at:100,mult:5,label:'×5'},{at:200,mult:10,label:'×10'},{at:500,mult:25,label:'×25'}]},
    ],
    managers: [
      {id:0,bizId:0,name:'Jana Jahodová',emoji:'👩‍🌾',desc:'Automatizuje jahodník',price:25},
      {id:1,bizId:1,name:'Karel Mrkvák',emoji:'👨‍🌾',desc:'Automatizuje mrkev',price:500},
      {id:2,bizId:2,name:'Tomáš Rajčeta',emoji:'🧑‍🌾',desc:'Automatizuje rajčata',price:5000},
      {id:3,bizId:3,name:'Blanka Borůvka',emoji:'👩‍💼',desc:'Automatizuje borůvky',price:50000},
      {id:4,bizId:4,name:'Bořek Brokolice',emoji:'🧑‍💼',desc:'Automatizuje brokolici',price:500000},
      {id:5,bizId:5,name:'Viktor Vinohrad',emoji:'👔',desc:'Automatizuje hrozny',price:5000000},
      {id:6,bizId:6,name:'Markéta Melounová',emoji:'👗',desc:'Automatizuje melouny',price:50000000},
      {id:7,bizId:7,name:'Avi Avokádo',emoji:'🤵',desc:'Automatizuje avokádo',price:500000000},
      {id:8,bizId:8,name:'Anežka Ananas',emoji:'👑',desc:'Automatizuje ananas',price:5000000000},
      {id:9,bizId:9,name:'Chilli Khan',emoji:'🎩',desc:'Automatizuje chilli',price:50000000000},
    ],
    upgrades: [
      {id:0, bizId:0,name:'Lepší půda',       emoji:'🍓',desc:'Kompost a mulč zdvojnásobí výnos jahod',                              price:100,       mult:2},
      {id:1, bizId:0,name:'Závlahový systém', emoji:'💧',desc:'Kapková závlaha ve správný čas – trojnásobná úroda',                  price:8000,      mult:3},
      {id:2, bizId:0,name:'Skleníkové jahody',emoji:'🏠',desc:'Vyhřívaný skleník = sklizeň 365 dní v roce, 5× více',                price:500000,    mult:5},
      {id:3, bizId:1,name:'Hnojivo premium',  emoji:'🥕',desc:'NPK granule urychlí klíčení a zdvojnásobí výnos mrkve',              price:1000,      mult:2},
      {id:4, bizId:1,name:'Kombajn na mrkev', emoji:'🚜',desc:'GPS kombajn pokryje 3× více řad najednou bez ztráty',                price:80000,     mult:3},
      {id:5, bizId:1,name:'GMO mrkev',        emoji:'🧬',desc:'Šlechtěný hybrid nese 5× více mrkví na m², odolný vůči suchu',       price:5000000,   mult:5},
      {id:6, bizId:2,name:'Solární skleník',  emoji:'☀️',desc:'LED osvětlení napájené solárními panely – rajčata rostou i v noci',   price:10000,     mult:2},
      {id:7, bizId:2,name:'Hydroponika',      emoji:'🌊',desc:'Kořeny visí ve výživném roztoku bez půdy – 3× rychlejší růst',       price:800000,    mult:3},
      {id:8, bizId:2,name:'Rajčatová věž',    emoji:'🏗️',desc:'5patrová vertikální věž – 5× více rostlin na stejné podlahové ploše',price:50000000,  mult:5},
      {id:9, bizId:3,name:'Kyselá půda',      emoji:'🫐',desc:'Rašelina sníží pH na 4.5 – borůvky milují kyselé prostředí, 2× více',price:100000,    mult:2},
      {id:10,bizId:3,name:'Mykorrhiza',       emoji:'🍄',desc:'Houbová síť rozšíří kořeny do celé půdy – 3× lepší příjem živin',    price:8000000,   mult:3},
      {id:11,bizId:3,name:'Borůvkový sad+',   emoji:'🌲',desc:'Rozšíříme plantáž na sousední pozemky – 5× více keřů celkem',       price:500000000, mult:5},
      {id:12,bizId:4,name:'Bio certifikát',   emoji:'🥦',desc:'EU bio certifikát otevře prémiové trhy s 2× vyšší výkupní cenou',   price:1000000,   mult:2},
      {id:13,bizId:4,name:'Chladírenský vůz', emoji:'🚛',desc:'Chladicí vůz rozveze čerstvou brokolici do 3× více obchodů denně',  price:80000000,  mult:3},
      {id:14,bizId:4,name:'Export do EU',     emoji:'🇪🇺',desc:'Vývozní licence do 5 zemí EU – prodej za vyšší ceny, 5× obrat',    price:5e9,       mult:5},
      {id:15,bizId:5,name:'Starý vinohrad',   emoji:'🍇',desc:'Révy starší 30 let dávají 2× více – sklizeň o polovinu rychlejší',  price:10000000,  mult:2, timerDiv:2},
      {id:16,bizId:5,name:'Vinný sklep',      emoji:'🏚️',desc:'Vlastní zrání v dubových sudech zdvojí cenu – cyklus o polovinu',   price:800000000, mult:2, timerDiv:2},
      {id:17,bizId:5,name:'Château label',    emoji:'🍷',desc:'Luxusní etiketa = 2× vyšší prodejní cena, rychlejší odbyt',          price:5e10,      mult:2, timerDiv:2},
      {id:18,bizId:6,name:'Včelí opylovači',  emoji:'🐝',desc:'Vlastní úly v sadu zdvojnásobí opylení – sklizeň o polovinu rychleji',price:100000000,mult:2, timerDiv:2},
      {id:19,bizId:6,name:'Prémiové semínko', emoji:'🌱',desc:'Japonská Densuke odrůda nese 2× větší melouny, kratší vegetace',    price:8e9,       mult:2, timerDiv:2},
      {id:20,bizId:6,name:'Megameloun',       emoji:'🍉',desc:'20kg rekordní plody = 2× vyšší výkupní cena, efektivnější sklizeň', price:5e11,      mult:2, timerDiv:2},
      {id:21,bizId:7,name:'Kalifornský sad',  emoji:'🥑',desc:'Teplé klima Kalifornie umožní celoroční sklizeň – 2× více avokád',  price:1e9,       mult:2, timerDiv:2},
      {id:22,bizId:7,name:'Influencer deal',  emoji:'📱',desc:'Virální TikTok kampaň zdvojnásobí poptávku – sklízíme rychleji',    price:8e10,      mult:2, timerDiv:2},
      {id:23,bizId:7,name:'Avokádo futures',  emoji:'📈',desc:'Spekulace na komoditní burze = 2× vyšší prodejní cena za várku',    price:5e12,      mult:2, timerDiv:2},
      {id:24,bizId:8,name:'Tropický skleník', emoji:'🍍',desc:'Simulace tropického klimatu zkrátí vegetaci – 2× rychlejší výnos',  price:1e10,      mult:2, timerDiv:2},
      {id:25,bizId:8,name:'Letecký export',   emoji:'✈️',desc:'Letecká přeprava do Evropy = 2× vyšší cena, kratší prodejní cyklus',price:8e11,      mult:2, timerDiv:2},
      {id:26,bizId:8,name:'Ananas imperium',  emoji:'👑',desc:'Monopol na trhu – diktujeme ceny a podmínky, 2× vyšší marže',      price:5e13,      mult:2, timerDiv:2},
      {id:27,bizId:9,name:'Ghost pepper',     emoji:'🌶️',desc:'Nejpálivější odrůda světa (2M Scoville) = 2× vyšší cena na trhu',  price:1e11,      mult:2, timerDiv:2},
      {id:28,bizId:9,name:'Omáčky & export',  emoji:'🔥',desc:'Vlastní Sriracha značka zdvojnásobí hodnotu – rychlejší výrobní cyklus',price:8e12,  mult:2, timerDiv:2},
      {id:29,bizId:9,name:'Chilli světovláda',emoji:'🌍',desc:'Distribuce do 50 zemí – 2× vyšší obrat a kratší dodací lhůty',     price:5e14,      mult:2, timerDiv:2},
    ],
    globalUpgrades: [
      {id:0, name:'Farmářská revoluce',     emoji:'🌱', desc:'Dvojnásobný příjem ze VŠECH farem', price:50000},
      {id:1, name:'Agrární technologie',    emoji:'🚜', desc:'Dvojnásobný příjem ze VŠECH farem', price:5000000},
      {id:2, name:'Průmyslová farma',       emoji:'🏭', desc:'Dvojnásobný příjem ze VŠECH farem', price:500000000},
      {id:3, name:'MegaFarm Corp',          emoji:'💎', desc:'Dvojnásobný příjem ze VŠECH farem', price:50000000000},
      {id:4, name:'Globální agro impérium', emoji:'🏆', desc:'Dvojnásobný příjem ze VŠECH farem', price:5e12},
    ],
  },

  // ── LEVEL 1: Vodní mlýn ───────────────────────
  {
    id: 1,
    name: 'Vodní mlýn',
    emoji: '🏚️',
    desc: 'Zdědil jsi starý vodní mlýn na řece. Začínáš prostým mletím pšenice, postupně stavíš celé pekařské impérium.',
    color: '#D4A017',
    businesses: [
      { id:0, name:'Mlýnské kolo',        emoji:'⚙️',  color:'#8B6914', bg:'rgba(139,105,20,0.15)',
        baseCost:4, baseIncome:1.0, timer:1.5, unlockCost:0,
        milestones:[{at:10,mult:2,label:'×2'},{at:25,mult:3,label:'×3'},{at:50,mult:2,label:'×2'},{at:100,mult:5,label:'×5'},{at:200,mult:2,label:'×2'},{at:300,mult:10,label:'×10'},{at:500,mult:2,label:'×2'}]},
      { id:1, name:'Pšeničné pole',       emoji:'🌾',  color:'#D4A017', bg:'rgba(212,160,23,0.15)',
        baseCost:60, baseIncome:8, timer:3, unlockCost:0,
        milestones:[{at:10,mult:2,label:'×2'},{at:25,mult:2,label:'×2'},{at:50,mult:3,label:'×3'},{at:100,mult:2,label:'×2'},{at:200,mult:5,label:'×5'},{at:400,mult:2,label:'×2'}]},
      { id:2, name:'Mlecí kámen',         emoji:'🪨',  color:'#9E8B75', bg:'rgba(158,139,117,0.12)',
        baseCost:720, baseIncome:60, timer:6, unlockCost:200,
        milestones:[{at:10,mult:2,label:'×2'},{at:25,mult:3,label:'×3'},{at:75,mult:2,label:'×2'},{at:100,mult:2,label:'×2'},{at:200,mult:5,label:'×5'},{at:300,mult:3,label:'×3'}]},
      { id:3, name:'Sýpka',               emoji:'🏚️',  color:'#C47A2B', bg:'rgba(196,122,43,0.15)',
        baseCost:8640, baseIncome:500, timer:12, unlockCost:2000,
        milestones:[{at:10,mult:2,label:'×2'},{at:25,mult:2,label:'×2'},{at:50,mult:5,label:'×5'},{at:100,mult:2,label:'×2'},{at:250,mult:3,label:'×3'},{at:500,mult:10,label:'×10'}]},
      { id:4, name:'Moučný sklad',        emoji:'🛖',  color:'#BFA980', bg:'rgba(191,169,128,0.15)',
        baseCost:103680, baseIncome:4000, timer:24, unlockCost:20000,
        milestones:[{at:10,mult:2,label:'×2'},{at:25,mult:2,label:'×2'},{at:50,mult:3,label:'×3'},{at:100,mult:5,label:'×5'},{at:200,mult:2,label:'×2'},{at:400,mult:5,label:'×5'}]},
      { id:5, name:'Hnětací dílna',       emoji:'🤲',  color:'#D4956A', bg:'rgba(212,149,106,0.15)',
        baseCost:1244160, baseIncome:30000, timer:48, unlockCost:200000,
        milestones:[{at:10,mult:2,label:'×2'},{at:25,mult:3,label:'×3'},{at:50,mult:2,label:'×2'},{at:100,mult:5,label:'×5'},{at:200,mult:3,label:'×3'},{at:300,mult:2,label:'×2'}]},
      { id:6, name:'Kváskovna',           emoji:'🧫',  color:'#7BAF5E', bg:'rgba(123,175,94,0.12)',
        baseCost:14929920, baseIncome:200000, timer:96, unlockCost:2000000,
        milestones:[{at:10,mult:2,label:'×2'},{at:25,mult:2,label:'×2'},{at:50,mult:3,label:'×3'},{at:100,mult:10,label:'×10'},{at:200,mult:2,label:'×2'},{at:350,mult:5,label:'×5'}]},
      { id:7, name:'Chlebová pec',        emoji:'🔥',  color:'#E8622A', bg:'rgba(232,98,42,0.12)',
        baseCost:179159040, baseIncome:1500000, timer:180, unlockCost:25000000,
        milestones:[{at:10,mult:2,label:'×2'},{at:25,mult:5,label:'×5'},{at:50,mult:2,label:'×2'},{at:100,mult:3,label:'×3'},{at:200,mult:5,label:'×5'},{at:400,mult:2,label:'×2'}]},
      { id:8, name:'Pekárna',             emoji:'🥖',  color:'#C8860A', bg:'rgba(200,134,10,0.12)',
        baseCost:2149908480, baseIncome:12000000, timer:360, unlockCost:300000000,
        milestones:[{at:10,mult:2,label:'×2'},{at:25,mult:3,label:'×3'},{at:50,mult:5,label:'×5'},{at:100,mult:2,label:'×2'},{at:200,mult:10,label:'×10'},{at:300,mult:3,label:'×3'}]},
      { id:9, name:'Císařská pekárna',    emoji:'👑',  color:'#FFD700', bg:'rgba(255,215,0,0.12)',
        baseCost:25798901760, baseIncome:100000000, timer:600, unlockCost:3000000000,
        milestones:[{at:10,mult:2,label:'×2'},{at:25,mult:5,label:'×5'},{at:50,mult:3,label:'×3'},{at:100,mult:5,label:'×5'},{at:200,mult:10,label:'×10'},{at:500,mult:25,label:'×25'}]},
    ],
    managers: [
      {id:0,bizId:0,name:'Mlynář Vašek',       emoji:'👴',  desc:'Automatizuje mlýnské kolo',price:25},
      {id:1,bizId:1,name:'Rolník Frantík',      emoji:'👨‍🌾', desc:'Automatizuje pšeničné pole',price:500},
      {id:2,bizId:2,name:'Kamenář Beneš',       emoji:'⛏️',  desc:'Automatizuje mlecí kámen',price:5000},
      {id:3,bizId:3,name:'Správce Zrnovský',    emoji:'🌾',  desc:'Automatizuje sýpku',price:50000},
      {id:4,bizId:4,name:'Skladník Mouček',     emoji:'📦',  desc:'Automatizuje moučný sklad',price:500000},
      {id:5,bizId:5,name:'Pekařský učeň Jarda',emoji:'🧑‍🍳', desc:'Automatizuje hnětací dílnu',price:5000000},
      {id:6,bizId:6,name:'Kvasinkář Ferda',     emoji:'🔬',  desc:'Automatizuje kváskování',price:50000000},
      {id:7,bizId:7,name:'Topič Uhlíř',         emoji:'🔥',  desc:'Automatizuje chlebovou pec',price:500000000},
      {id:8,bizId:8,name:'Mistr pekař Novák',   emoji:'👨‍🍳', desc:'Automatizuje pekárnu',price:5000000000},
      {id:9,bizId:9,name:'Šéfkuchař Brillat',   emoji:'🎩',  desc:'Automatizuje císařskou pekárnu',price:50000000000},
    ],
    upgrades: [
      {id:0,  bizId:0, name:'Dubové lopatky',          emoji:'🌊', desc:'Silnější dubové lopatky točí kolo 2× rychleji',                            price:100,       mult:2},
      {id:1,  bizId:0, name:'Železná osa',             emoji:'⚙️', desc:'Ocelová osa snižuje tření — trojnásobný výkon mlýna',                      price:8000,      mult:3},
      {id:2,  bizId:0, name:'Turbínové kolo',          emoji:'💧', desc:'Moderní turbína místo starého kola — 5× více energie z řeky',              price:500000,    mult:5},
      {id:3,  bizId:1, name:'Ozimá pšenice',           emoji:'🌾', desc:'Zimní odrůda dá 2× více zrna na stejné ploše',                            price:1000,      mult:2},
      {id:4,  bizId:1, name:'Koňský pluh',             emoji:'🐴', desc:'Koňský potah zorá pole 3× rychleji než ručně',                            price:80000,     mult:3},
      {id:5,  bizId:1, name:'Střídání plodin',         emoji:'🔄', desc:'Vědecké střídání plodin — 5× vyšší úroda bez vyčerpání půdy',             price:5000000,   mult:5},
      {id:6,  bizId:2, name:'Francouzský granit',      emoji:'🪨', desc:'Tvrdší kámen mele jemněji — 2× vyšší výtěžnost bílé mouky',               price:10000,     mult:2},
      {id:7,  bizId:2, name:'Dvojitý mlýnek',          emoji:'⚙️', desc:'Dva kameny najednou — 3× rychlejší mletí bez přestávky',                  price:800000,    mult:3},
      {id:8,  bizId:2, name:'Válcový mlýn',            emoji:'🏭', desc:'Průmyslové válce nahradí kámen — 5× jemnější mouka za méně času',         price:50000000,  mult:5},
      {id:9,  bizId:3, name:'Větrané podlahy',         emoji:'💨', desc:'Provětrávání zabraňuje plísni — 2× déle vydrží zrno čerstvé',             price:100000,    mult:2},
      {id:10, bizId:3, name:'Krysí hlídka',            emoji:'🐱', desc:'Mlynářské kočky chrání zásoby — 3× méně ztrát při skladování',           price:8000000,   mult:3},
      {id:11, bizId:3, name:'Kamenná sýpka',           emoji:'🏰', desc:'Pevná kamenná stavba pojme 5× více zrna bez rizika požáru',              price:500000000, mult:5},
      {id:12, bizId:4, name:'Suché prostory',          emoji:'🛖', desc:'Odvlhčení skladu zabrání hrudkování — 2× kvalitnější mouka',              price:1000000,   mult:2},
      {id:13, bizId:4, name:'Pytlovací stroj',         emoji:'⚙️', desc:'Automatické pytlování zrychlí expedici — 3× vyšší průtok skladu',         price:80000000,  mult:3},
      {id:14, bizId:4, name:'Chladírenský sklad',      emoji:'❄️', desc:'Chlazení zachová kvalitu mouky — 5× vyšší výkupní cena pro pekaře',       price:5e9,       mult:5},
      {id:15, bizId:5, name:'Recept praotců',          emoji:'📜', desc:'Starý rodinný recept na těsto — 2× lepší vláčnost chleba',                price:10000000,  mult:2, timerDiv:2},
      {id:16, bizId:5, name:'Hnětací stroj',           emoji:'🤲', desc:'Mechanický hnětač zvládne 3× více těsta najednou',                        price:800000000, mult:2, timerDiv:2},
      {id:17, bizId:5, name:'Automat na těsto',        emoji:'🏭', desc:'Plně automatická linka — těsto míchá 2× rychleji než ručně',              price:5e10,      mult:2, timerDiv:2},
      {id:18, bizId:6, name:'Stoletý kvásek',          emoji:'🧫', desc:'Tradiční kvásek z roku 1890 — 2× lepší chuť a vyšší cena chleba',         price:100000000, mult:2, timerDiv:2},
      {id:19, bizId:6, name:'Řízená fermentace',       emoji:'🌡️', desc:'Kontrola teploty kvašení — 3× konzistentnější kvalita každý den',         price:8e9,       mult:2, timerDiv:2},
      {id:20, bizId:6, name:'Laboratorní kmen',        emoji:'🔬', desc:'Speciálně šlechtěná kultura kvasinek — 2× rychlejší kynutí',              price:5e11,      mult:2, timerDiv:2},
      {id:21, bizId:7, name:'Dubové dřevo',            emoji:'🔥', desc:'Kvalitní dubové palivo — 2× vyšší teplota, lepší kůrka',                  price:1e9,       mult:2, timerDiv:2},
      {id:22, bizId:7, name:'Kamenná klenba',          emoji:'🏛️', desc:'Klenba akumuluje teplo — pec udrží teplotu 3× déle bez přikládání',       price:8e10,      mult:2, timerDiv:2},
      {id:23, bizId:7, name:'Rotační buben',           emoji:'⚙️', desc:'Otáčivý buben peče chléb rovnoměrně — 2× méně propálených bochníků',      price:5e12,      mult:2, timerDiv:2},
      {id:24, bizId:8, name:'Ranní rozvoz',            emoji:'🛒', desc:'Vlastní vozík rozveze chléb do vesnic — 2× více zákazníků denně',         price:1e10,      mult:2, timerDiv:2},
      {id:25, bizId:8, name:'Královský dodavatel',     emoji:'👑', desc:'Smlouva s vrchností — 3× vyšší výkupní cena za každý bochník',            price:8e11,      mult:2, timerDiv:2},
      {id:26, bizId:8, name:'Pekařský cech',           emoji:'🏅', desc:'Členství v cechu otevře trhy v celém kraji — 2× větší odbyt',             price:5e13,      mult:2, timerDiv:2},
      {id:27, bizId:9, name:'Vídeňský recept',         emoji:'🥐', desc:'Tajná vídeňská receptura — 2× vyšší cena za každý produkt',               price:1e11,      mult:2, timerDiv:2},
      {id:28, bizId:9, name:'Zlatá pečeť',             emoji:'🔏', desc:'Císařská zlatá pečeť na každém bochníku — 3× prémiová cena',              price:8e12,      mult:2, timerDiv:2},
      {id:29, bizId:9, name:'Dodávky do Vídně',        emoji:'🏰', desc:'Export do císařského dvora — monopol na nejluxusnější chléb, 2× obrat',   price:5e14,      mult:2, timerDiv:2},
    ],
    globalUpgrades: [
      {id:0, name:'Mlynářská revoluce',     emoji:'⚙️', desc:'Dvojnásobný příjem ze VŠECH provozů', price:50000},
      {id:1, name:'Vodní technologie',      emoji:'💧', desc:'Dvojnásobný příjem ze VŠECH provozů', price:5000000},
      {id:2, name:'Průmyslový mlýn',        emoji:'🏭', desc:'Dvojnásobný příjem ze VŠECH provozů', price:500000000},
      {id:3, name:'MegaPekárna s.r.o.',     emoji:'💎', desc:'Dvojnásobný příjem ze VŠECH provozů', price:50000000000},
      {id:4, name:'Císařský monopol',       emoji:'🏆', desc:'Dvojnásobný příjem ze VŠECH provozů', price:5e12},
    ],
  },
];

// ─── Mutable exports — swapped by setActiveLevel() ───
export let BUSINESSES     = LEVELS[0].businesses;
export let MANAGERS       = LEVELS[0].managers;
export let UPGRADES       = LEVELS[0].upgrades;
export let GLOBAL_UPGRADES = LEVELS[0].globalUpgrades;

export const COST_GROWTH = 1.15;
export const COST_MULT   = 0.20;  // globální sleva — nákup do maxima stojí ~20 % původní ceny

export function setActiveLevel(levelId) {
  const lvl = LEVELS[levelId];
  if (!lvl) return;
  BUSINESSES      = lvl.businesses;
  MANAGERS        = lvl.managers;
  UPGRADES        = lvl.upgrades;
  GLOBAL_UPGRADES = lvl.globalUpgrades;
}
